import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import WishlistProvider from "@/context/WishListContext";
import {CartProvider} from "@/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
         <CartProvider>
            <WishlistProvider>
            <Navbar />
            <main className="max-w-6xl mx-auto">{children}</main>
            </WishlistProvider>
          </CartProvider>

          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
